$('#carousel1').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        768:{
            items:4
        },
        992:{
            items:5
        }
    }
})